spring:
  output:
  ansi:
  enabled: always
server:
  port: 8081
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: utf-8
age: 19
name: Cyber_Kaka
personinfo:
  name: Cyber-Kaka
  age: 13